export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST = 'FETCH_POST'
export const FETCH_POSTS_BY_SCORE = 'FETCH_POSTS_BY_SCORE'

export const FETCH_COMMENTS = 'FETCH_COMMMENT'
export const FETCH_COMMENTS_BY_SCORE = 'FETCH_COMMENTS_BY_SCORE'

export const CHANGE_USER = 'CHANGE_USER'
